### PR TITLE
Progress Tracker Bar Added

### PR DESCRIPTION
**Pull request by Trishashetty11**
**Key Features**
**Task Management:** Users can add tasks, mark them as completed, and see their progress.
**Progress Tracking:** A dynamic progress bar reflects the percentage of completed tasks.
**Responsive Design:** The layout is designed using Tailwind CSS for a modern and responsive user experience.
**Changes Made**
Developed the HTML structure for tasks and calendar sections.
Styled components using Tailwind CSS for a clean look.
Added JavaScript functionality to handle task addition and progress updates.

### CODE REVIEW

**Comment by avinash201199** [comment]
I accepted previous pr , please resolve conflicts

**Comment by Trishashetty11** [comment]
Sure ,I'll do it As soon as possible..

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Trishashetty11** [comment]
@avinash201199 I've Resolved the Conflicts.

**Comment by Trishashetty11** [comment]
@avinash201199 **Please Merge this PR**

**Comment by avinash201199** [comment]
Thank you for your contribution :)

**Comment by avinash201199** [comment]
image
reverting this pr as css file is removed

**Pull request merged**
