### PR TITLE
UI Changes - Issue #8

### PR DESCRIPTION
**Pull request by vidhisinha2002**
Added Placeholder
Add Button Hover To Black
Dropdown Text as Black
Capitalisation
opens

### CODE REVIEW

**Comment by avinash201199** [comment]
pr merged , now please close the issue :)
contribute to more repo

**Comment by avinash201199** [comment]
@vidhisinha2002  hey, items are not displayed after merging the pr :(
please solve the issue

**Comment by vidhisinha2002** [comment]
@avinash201199 Hey, before doing the changes it was like that. I even tried undoing all the changes I did locally but it's the same.
I have the original copy(before merging) but in that also items are not displayed.

**Comment by vidhisinha2002** [comment]
@avinash201199 But yeah we will look into it:)

**Pull request merged**
