### PR TITLE
Modified the dark mode and toggler button

### PR DESCRIPTION
**Pull request by helloArnab**
Modified the dark more toggler button and the dark theme.
<br>
Screenshot (123)

### CODE REVIEW

**Comment by avinash201199** [comment]
resolve conflicts

**Comment by helloArnab** [comment]
done :)

**Comment by avinash201199** [comment]
please do again

**Comment by helloArnab** [comment]
done again :)

**Comment by avinash201199** [comment]
Thank you :)

**Comment by avinash201199** [comment]
image

dard mode is not working , can you please solve the bug

**Comment by helloArnab** [comment]
Ok i am looking after the issue

**Comment by helloArnab** [comment]
I have checked the website in 3 other devices and different browser and it is working fine. I think you have some problem.

<br>

WhatsApp Image 2022-10-16 at 2 40 44 PM

**Comment by avinash201199** [comment]
it's working fine , thank you !

**Pull request merged**
