### PR TITLE
Delete All Button and Empty Space Fixed ( Issue #133 )

### PR DESCRIPTION
**Pull request by R0Y4L23**
The Delete All Button is hidden for empty list. Instead a Text is shown in the empty space in the middle.
The Pull Request is for Issue #133 
pull_request1

### CODE REVIEW

**Comment by avinash201199** [comment]
please resolve branch conflicts

**Comment by R0Y4L23** [comment]
> please resolve branch conflicts

Please Check , the conflict is resolved

**Comment by avinash201199** [comment]
still

**Comment by avinash201199** [comment]
delete and fork again to do your changes

**Pull request closed without merging**
