### PR TITLE
Dark_mode_added.

### PR DESCRIPTION
**Pull request by anivaish**
Hi there @avinash201199 , Code is ready. I have successfully added a toggle button for dark mode. The website is working fine and looking good in dark mode too. I am sending you pull request please merge it. If any issue then let me know.

Screenshot (457)
Screenshot (458)
Screenshot (459)
Screenshot (454)
Screenshot (455)
Screenshot (456)

### CODE REVIEW

**Comment by avinash201199** [comment]
great work :) 
please resolve branch conflict

**Comment by anivaish** [comment]
Sorry for the inconvenience. I have done the significan changes. Please merge my code sir.

**Comment by anivaish** [comment]
thanks sir.

**Comment by avinash201199** [comment]
image

may be little bug in the code , please check

**Comment by avinash201199** [comment]
reverting the pull request

**Comment by avinash201199** [comment]
please make pr again , delete the repo and fork again to do your changes

**Pull request merged**
