### PR TITLE
fix: social media icons in footer

### PR DESCRIPTION
**Pull request by supminn**
#19 fix: The images set to the relative path was giving an issue.

### CODE REVIEW

**Comment by avinash201199** [comment]
image

can you work more on desktop view ?

**Comment by avinash201199** [comment]
IMG_20211002_234901
 Works good in mobile view

**Comment by supminn** [comment]
Sure, I will do that. 
Are you not able to view the icons on desktop view? Or should I be working on improving the styling for it?

**Comment by avinash201199** [comment]
> Sure, I will do that. Are you not able to view the icons on desktop view? Or should I be working on improving the styling for it?

It is visible but you should work on improving the styling :)
thanks you are doing good work .

**Pull request merged**
